on:
  push:
    branches:
      - master
name: release-please
jobs:
  list_modules:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(find . -type f -name 'Dockerfile' | awk -F\/ '{print $3"/"$4}' | jq -Rsc '. / "\n" - [""]')"
  release-please:
    name: release-${{ matrix.subject }}
    runs-on: ubuntu-latest
    needs: list_modules
    strategy:
      matrix:
        subject: ${{fromJSON(needs.list_modules.outputs.matrix)}}
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          monorepo-tags: true
          release-type: python
          command: github-release
          path: thumbor_plugins/${{ matrix.subject }}
