
name: Release packages

on:
  # workflow_run:
  #   workflows: ["Run tests"]
  #   branches: [master]
  #   types:
  #     - completed
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  list_packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(find thumbor_plugins -type f -name 'setup.py' | awk -F\/ '{print $2"/"$3}' | jq -Rsc '. / "\n" - [""]')"
  release:
    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    needs: list_packages
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        package: ${{fromJSON(needs.list_packages.outputs.matrix)}}
    defaults:
      run:
        working-directory: ./thumbor_plugins/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Prepare build environment
        run: |
          pip install -U pip
          pip install -U build
          echo "PACKAGE_NAME=$(python setup.py --name)" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(python setup.py --version)" >> $GITHUB_ENV
          echo "TAG_NAME=$(python setup.py --fullname)" >> $GITHUB_ENV
      - name: Check if version already exists
        id: exist
        run: |
          set -o pipefail
          echo "::set-output name=result::$(pip index versions $PACKAGE_NAME | grep $PACKAGE_VERSION >> /dev/null; echo $?)"
      - name: Get previous tag
        id: previous_tag
        uses: SOLIDSoftworks/semver-tags@1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: "${{ env.PACKAGE_NAME }}-"
          default-version: '0.0.1'
          prerelease: 'alpha'
          dry-run: true
      - run: |
          echo "${{ steps.previous_tag.outputs }}"
          echo "${{ steps.previous_tag.outputs.previous-version }}"
      # - uses: codfish/semantic-release-action@be6feadd39b5e45629542f3bc9403b7adcff9e3b
      #   with:
      #     dry_run: true
      #     tag_format: 'v${version}'
      #     additional_packages: |
      #       ['semantic-release-commit-filter']
      #     extends: 'semantic-release-commit-filter'
      #     plugins: |
      #       ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github']
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.7.0
        with:
          dry_run: true
          branches: |
            [
              '.*',
            ]
          extra_plugins: |
            @semantic-release/changelog@3.0.0
            @semantic-release/git
            semantic-release-commit-filter
          extends: |
            'semantic-release-commit-filter'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        if: ${{ !steps.exist.outputs.result }}
        run: python -m build
      - name: Publish a Python distribution to PyPI
        if: ${{ !steps.exist.outputs.result }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: thumbor_plugins/${{ matrix.package }}/dist
