
name: Release packages

on: [push, pull_request]

jobs:
  list_packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(find thumbor_plugins -type f -name 'setup.py' | awk -F\/ '{print $2"/"$3}' | jq -Rsc '. / "\n" - [""]')"
  release:
    name: ${{ matrix.subject }}
    runs-on: ubuntu-latest
    needs: list_packages
    strategy:
      matrix:
        subject: ${{fromJSON(needs.list_packages.outputs.matrix)}}
    defaults:
      run:
        working-directory: ./thumbor_plugins/${{ matrix.subject }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Prepare build environment
        run: |
          pip install -U pip
          pip install -U build
      - name: Build package
        run: python -m build && ls dist/
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
